version: "3.9"
services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
#    environment:
#      DB_PASSWD: "Dima123"
      # DB_SID: "OraDoc"
#      DB_DOMAIN: "my.domain.com"
    volumes:
      - ./opt/oracle/oradata:/opt/oracle/oradata
    ports:
      - "1526:1521"
      - "5500:5500"
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 4G